### ISSUE TITLE
Python example?

### ISSUE THREAD

**Issue by bscully27** [metal-stack/metal-python#50]
Provide a python example?

**Comment by Gerrit91** [comment]
Hi! There is an example file in the root of the directory: https://github.com/metal-stack/metal-python/blob/master/example.py

You can also check more sophisticated examples in the [metal-ansible-modules](https://github.com/metal-stack/metal-ansible-modules) project.

**Comment by bscully27** [comment]
I didnt see any user-friendly examples.

I'm looking for something like, "To get the past year prices of
XAU,XAG,XCU,ALU  , the url would be:
https://www.metals-api.com/api/timeseries?access_key=MY_ACCESS_KEY&start=2018-01-01&end=2022-01-13&base=USD&symbols=XAU,XAG,XCU,ALU
"

Then additional code of, in python3, "import ......"


Right now I'm getting an error.

{"success":false,"error":{"code":501,"type":"invalid_timeframe","info":"No
or an invalid timeframe has been specified."}}

**Comment by Gerrit91** [comment]
Thanks for clarification. The page you are referring to is a completely different API / project / company. This project belongs to the metal-stack organization, we are provisioning Kubernetes on bare metal, elastic cloud infrastructure: https://metal-stack.io/
